services:
  db:
    image: mysql:lts
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql/
      - ./mysql/files:/var/lib/mysql-files/
    environment:
      MYSQL_ROOT_PASSWORD: secret

